routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();
Route::middleware(['auth'])->namespace('Backend')->prefix('admin')->group(function() {
    // Route::resource('users', 'UsersController');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Tymon\JWTAuth\Contracts\JWTSubject;
use Backpack\Base\app\Notifications\ResetPasswordNotification as ResetPasswordNotification;

class User extends Authenticatable implements JWTSubject
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'last_login_at',
        'last_login_ip',
        'current_login_at',
        'current_login_ip',
        'is_admin',
        'company_name',
        'title',
        'city',
        'state',
        'country',
        'telephone'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $dates = [
        'current_login_at', 'last_login_at'
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $visible = [
        'id',
        'name',
        'email',
        'password',
        'last_login_at',
        'last_login_ip',
        'current_login_at',
        'current_login_ip',
        'is_admin',
        'company_name',
        'title',
        'city',
        'state',
        'country',
        'telephone',

        'permissions',
        'permission_for_mkt'
    ];

    /**
     * @param string $value
     *
     * @return string
     */
    public function getCreatedAtAttribute($value)
    {
        return date("m/d/Y H:m", strtotime($value));
    }
    
    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }

    /**
     * The permissions that belong to the user.
     */
    public function permissions()
    {
        return $this->belongsToMany(TherapyArea::class, 'therapy_area_user')
                ->withPivot(
                    'disease_prevalence_ana',
                    'treatment_mapping',
                    'patient_forecasting',
                    'diagnotics'
                );
    }

    /**
     * The permissions that belong to the user.
     */
    public function permission_for_mkt()
    {
        return $this->hasOne(MktPermission::class);
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Users\UserStore;
use App\Http\Requests\Users\UserUpdate;
use Prologue\Alerts\Facades\Alert;

use App\Models\User;
use App\Models\TherapyArea;
use App\Models\MktPermission;

class UsersController extends Controller
{
    /**
     * @var User
     */
    private $user;

    /**
     * @var TherapyArea
     */
    private $therapyArea;

    /**
     * @var MktPermission
     */
    private $mktPermission;

    /**
     * UsersController constructor.
     *
     * @param User $user
     * @param TherapyArea $therapyArea
     * @param MktPermission $mktPermission
     */

    public function __construct(User $user, TherapyArea $therapyArea, MktPermission $mktPermission)
    {
        $this->user = $user;
        $this->therapyArea = $therapyArea;
        $this->mktPermission = $mktPermission;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $users = $this->user->paginate(20);
        return view('dashboard.users.index', compact('users'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('dashboard.users.create');
    }
    
    /**
     * @param int $id
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(int $id)
    {
        $user = $this->user
            ->findOrFail($id);
        return view('dashboard.users.edit', [ 
            'user' => $user
        ]);
    }

    /**
     * @param UserStore $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(UserStore $request)
    {
        $this->user->create([
            'email' => $request->get('email'),
            'name' => $request->get('name'),
            'password' => bcrypt($request->get('password')),
            'company_name' => $request->get('company_name'),
            'title' => $request->get('title'),
            'city' => $request->get('city') ?? '',
            'state' => $request->get('state') ?? '',
            'country' => $request->get('country'),
            'telephone' => $request->get('telephone'),
        ]);

        Alert::success('User successfully created')->flash();

        return redirect()->route('users.index')->with('alerts', Alert::all());
    }

    /**
     * @param UserUpdate $request
     *
     * @return JsonResponse
     */
    public function update(UserUpdate $request)
    {
        $id = $request->get('user_id');
        $queryParams = $request->validatedOnly();
        $user = $this->user
            ->findOrFail($id);
        $user->update([
        	'email' => $request->get('email'),
            'name' => $request->get('name'),
            'company_name' => $request->get('company_name'),
            'title' => $request->get('title'),
            'city' => $request->get('city'),
            'state' => $request->get('state'),
            'country' => $request->get('country'),
            'telephone' => $request->get('telephone'),
        ]);

        if (isset($queryParams['password'])) {
            $user->update([
                'password' => bcrypt($queryParams['password'])
            ]);
        }

        Alert::success('User successfully updated')->flash();

        return redirect()->route('users.index')->with('alerts', Alert::all());
    }

    /**
     * @param $id
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $this->user->findOrFail($id)->delete();

        Alert::success('User successfully deleted')->flash();

        return redirect()->route('users.index')->with('alerts', Alert::all());
    }

    
    public function compareOrder($a, $b)
    {
        return $a['id'] - $b['id'];
    }

    /**
     * @param int $id
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function editPermissions(int $id)
    {
        $user = $this->user
            ->with(['permissions', 'permission_for_mkt'])
            ->findOrFail($id)
            ->toArray();
        $therapyAreas =$this->therapyArea
            ->get()
            ->toArray();
        $permissions = $user['permissions'];
        foreach ($therapyAreas as $key => $therapyArea) {
            if (!in_array($therapyArea['id'], array_column($user['permissions'], 'id'))) {
                $permissions[] = $therapyArea;
            }
        }

        usort($permissions, [$this, 'compareOrder']);

        return view('dashboard.users.edit_permission', [ 
            'user' => $user,
            'permissions' => $permissions,
            'mkt_permission' => $user['permission_for_mkt']
        ]);
    }

    public function syncPivot($user, $queryParams, $name = 'disease_prevalence_ana') {
        foreach ($queryParams as $key => $queryParam) {
            $user->permissions()->sync([
                $key => [
                    $name => 1
                ]
            ], false);
        }
    }
    /**
     * @param int $id
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function savePermissions(int $id, Request $request)
    {
        
        $user = $this->user
            ->findOrFail($id);
        $user->permissions()->detach();
        $user->permission_for_mkt()->delete();

        $das = $request->get('disease_prevalence_ana');
        $tms = $request->get('treatment_mapping');
        $pfs = $request->get('patient_forecasting');
        $dgs = $request->get('diagnotics');
        if ($das) {
            $this->syncPivot($user, $das, 'disease_prevalence_ana');
        }
        if ($tms) {
            $this->syncPivot($user, $tms, 'treatment_mapping');
        }        
        if ($pfs) {
            $this->syncPivot($user, $pfs, 'patient_forecasting');
        }        
        if ($dgs) {
            $this->syncPivot($user, $dgs, 'diagnotics');
        }

        // save to mkt_permissions
        $mktPermission = $request->get('mkt_permission');
        if (isset($mktPermission)) {
            $this->mktPermission->create([
                'user_id' => $id,
                'total_market_view' => isset($mktPermission['total_market_view']) ? 1:0,
                'therapy_area_ana' => isset($mktPermission['therapy_area_ana']) ? 1:0,
                'brand_ana' => isset($mktPermission['brand_ana']) ? 1:0,
                'molecule_ana' => isset($mktPermission['molecule_ana']) ? 1:0,
            ]);
        }        

        Alert::success($user->name . ' has been privileged successfully')->flash();

        return redirect()->route('users.index')->with('alerts', Alert::all());
    }

}

resources/views/dashboard/users/create.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            Create New User
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
            <li><a href="{{ route('users.index') }}">Users</a></li>
            <li class="active">Create New User</li>
        </ol>
    </section>
@endsection


@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <a href="{{ route('users.index') }}"><i class="fa fa-angle-double-left"></i> Back to Users</a>
            <br>
            <br>
            <div class="box box-default">
                <div class="box-header with-border">
                    <div class="box-title">New User</div>
                </div>

                <div class="box-body">
                    <form method="post" action="{{ route('users.store') }}">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label>Name *</label>
                            <input type="text" class="form-control" name="name" required>
                            @if($errors->has('name'))
                                <span class="text-danger">{{ $errors->first('name') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Email *</label>
                            <input type="text" class="form-control" name="email" required>
                            @if($errors->has('email'))
                                <span class="text-danger">{{ $errors->first('email') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Set Password *</label>
                            <input type="text" class="form-control" name="password" required>
                            @if($errors->has('password'))
                                <span class="text-danger">{{ $errors->first('password') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Company Name *</label>
                            <input type="text" class="form-control" name="company_name" required>
                            @if($errors->has('company_name'))
                                <span class="text-danger">{{ $errors->first('company_name') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Title in the Company *</label>
                            <input type="text" class="form-control" name="title" required>
                            @if($errors->has('title'))
                                <span class="text-danger">{{ $errors->first('title') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>city</label>
                            <input type="text" class="form-control" name="city">
                            @if($errors->has('city'))
                                <span class="text-danger">{{ $errors->first('city') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>State/Province</label>
                            <input type="text" class="form-control" name="state">
                            @if($errors->has('state'))
                                <span class="text-danger">{{ $errors->first('state') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Country *</label>
                            <input type="text" class="form-control" name="country" required>
                            @if($errors->has('country'))
                                <span class="text-danger">{{ $errors->first('country') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Telephone *</label>
                            <input type="text" class="form-control" name="telephone" required>
                            @if($errors->has('telephone'))
                                <span class="text-danger">{{ $errors->first('telephone') }}</span>
                            @endif
                        </div>
                        <hr>
                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-sm btn-primary" id="submitForm">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/users/edit.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            Edit
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
            <li><a href="{{ route('users.index') }}">Users</a></li>
            <li class="active">Edit {{ $user->name }}</li>
        </ol>
    </section>
@endsection


@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <a href="{{ route('users.index') }}"><i class="fa fa-angle-double-left"></i> Back to Users</a>
            <br>
            <br>
            <div class="box box-default">
                <div class="box-header with-border">
                    <div class="box-title">Edit {{ $user->name }}</div>
                </div>

                <div class="box-body">
                    <form method="post" action="{{ route('users.update', $user->id) }}">
                        <input type="hidden" name="_method" value="patch">
                        <input type="hidden" name="user_id" value="{{ $user->id }}">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label>Name *</label>
                            <input type="text" class="form-control" name="name" @isset($user) value="{{ $user->name }}" @endisset required>
                            @if($errors->has('name'))
                                <span class="text-danger">{{ $errors->first('name') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Email *</label>
                            <input type="text" class="form-control" name="email" @isset($user) value="{{ $user->email }}" @endisset required>
                            @if($errors->has('email'))
                                <span class="text-danger">{{ $errors->first('email') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Company Name *</label>
                            <input type="text" class="form-control" name="company_name" @isset($user) value="{{ $user->company_name }}" @endisset required>
                            @if($errors->has('company_name'))
                                <span class="text-danger">{{ $errors->first('company_name') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Title in the Company *</label>
                            <input type="text" class="form-control" name="title" @isset($user) value="{{ $user->title }}" @endisset required>
                            @if($errors->has('title'))
                                <span class="text-danger">{{ $errors->first('title') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>city</label>
                            <input type="text" class="form-control" name="city" @isset($user) value="{{ $user->city }}" @endisset>
                            @if($errors->has('city'))
                                <span class="text-danger">{{ $errors->first('city') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>State/Province</label>
                            <input type="text" class="form-control" name="state" @isset($user) value="{{ $user->state }}" @endisset>
                            @if($errors->has('state'))
                                <span class="text-danger">{{ $errors->first('state') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Country *</label>
                            <input type="text" class="form-control" name="country" @isset($user) value="{{ $user->country }}" @endisset required>
                            @if($errors->has('country'))
                                <span class="text-danger">{{ $errors->first('country') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Telephone *</label>
                            <input type="text" class="form-control" name="telephone" @isset($user) value="{{ $user->telephone }}" @endisset required>
                            @if($errors->has('telephone'))
                                <span class="text-danger">{{ $errors->first('telephone') }}</span>
                            @endif
                        </div>
                        <hr>
                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-sm btn-primary" id="submitForm">Save</button>
                        </div>
                    </form>

                    <form method="post" action="{{ route('users.update', $user->id) }}">
                        <input type="hidden" name="_method" value="patch">
                        <input type="hidden" name="user_id" value="{{ $user->id }}">
                        {{ csrf_field() }}
                        <input type="hidden" class="form-control" name="name" @isset($user) value="{{ $user->name }}" @endisset>
                        <input type="hidden" class="form-control" name="email" @isset($user) value="{{ $user->email }}" @endisset>
                        <div class="form-group">
                            <label>Change Password</label>
                            <input type="text" class="form-control" name="password" @isset($user) value="" @endisset>
                            @if($errors->has('password'))
                                <span class="text-danger">{{ $errors->first('password') }}</span>
                            @endif
                        </div>
                        <hr>
                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-sm btn-primary" id="submitForm">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/users/index.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            Users
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
            <li class="active">Users</li>
        </ol>
    </section>
@endsection


@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="box box-default">
                <div class="box-header with-border">
                    <div class="box-title">Users ({{ $users->total() }})</div>
                    <a class="btn btn-xs btn-primary pull-right" href="{{ route('users.create') }}">
                        <i class="fa fa-plus-circle"></i> Create new User
                    </a>
                </div>

                <div class="box-body">
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Created at</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->created_at }}</td>
                                    <td>
                                        <form method="post" action="{{ route('users.destroy', $user->id) }}">
                                            <input type="hidden" name="_method" value="delete" />
                                            {!! csrf_field() !!}
                                            <button type="submit" class="btn btn-xs btn-danger pull-right remove">
                                                <i class="fa fa-trash"></i> Delete
                                            </button>                                            
                                        </form>
                                        <a class="btn btn-xs btn-default pull-right" href="{{ route('users.edit', $user->id) }}">
                                            <i class="fa fa-edit"></i> Edit
                                        </a>
                                        <a class="btn btn-xs btn-default pull-right" href="{{ route('users.permission', $user->id) }}">
                                            <i class="fa fa-lock"></i> Permission
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                {{ $users->links() }}
            </div>
        </div>
    </div>
@endsection